# JoinMessagePlus - Simple Join-Message Plugin
# This plugin uses MiniMessage as message syntax
#
# BungeeSupport:
#   Enabled: false/true - Activate this option if you only like to have Bungee Join/Quit-Messages. To use this feature you have to enable BungeeCord in the spigot.yml.
# AuthMeSupport:
#   Enabled: false/true - Activate this option if you only like to have Join/Quit-Messages if an user logs in successful using AuthMe.
# JoinMessage:
#   Enabled: true/false - Should the Join-Message be enabled.
#   Message: '&6[&a+&6] <player_name>/<player_displayname>' - Your custom Join-Message.
# QuitMessage:
#   Enabled: true/false - Should the Quit-Message be enabled.
#   Message: '&6[&4-&6] <player_name>/<player_displayname>' - Your custom Quit-Message.
#
Syntax: "minimessage" # can be vanilla or minimessage.
BungeeSupport:
  Enabled: false
AuthMeSupport:
  Enabled: false
JoinMessage:
  Enabled: true
  Message: '<#FFAA00>[<#55FF55>+</#55FF55>] <player_name> </#FFAA00>'
QuitMessage:
  Enabled: true
  Message: '<#FFAA00>[<#AA0000>-</#AA0000>] <player_name> </#FFAA00>'
