# JoinMessagePlus - Simple Join-Message Plugin
# This plugin uses MiniMessage as message syntax
#                  
# GlobalJoinMessage:
#   Enabled: true - Should the Global-Join-Message be enabled.
#   Message: '&6[&bGLOBAL&6] [&a+&6] <player_name>/<player_displayname>' - Your custom Global-Join-Message.
# GlobalQuitMessage:
#   Enabled: true - Should the Global-Quit-Message be enabled.
#   Message: '&6[&bGLOBAL&6] [&4-&6] <player_name>/<player_displayname>' - Your custom Global-Quit-Message.
#              
GlobalJoinMessage:
  Enabled: true
  Message: '<#FFAA00>[<#55FF55>+</#55FF55>] [<#55FFFF>GLOBAL</#55FFFF>] <player_name> </#FFAA00>'
GlobalQuitMessage:
  Enabled: true
  Message: '<#FFAA00>[<#AA0000>-</#AA0000>] [<#55FFFF>GLOBAL</#55FFFF>] <player_name> </#FFAA00>'
